version: '1.0.0.{build}'

platform: x64

branches:
  only:
    - master

image:
  - Visual Studio 2017

clone_folder: C:\gopath\src\github.com\rlj1202\go-wpd

environment:
  GOPATH: C:\gopath

install:
  - set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%GOPATH%\bin;C:\go\bin;%PATH%
  - echo %PATH%
  - go version
  - go env

build_script:
  - msbuild libgowpd/libgowpd.sln
  - go build -v
