version: '1.0.0.{build}'

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\rlj1202\go-wpd

environment:
  GOPATH: c:\gopath

install:
  - pacman --sync --noconfirm mingw-w64-x86_64-toolchain
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go build -v
